apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: lab-spring-boot-on-k8s
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
  workshops:
  - name: lab-spring-boot-on-k8s
    capacity: 1
    expires: 60m
    orphaned: 5m
