apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-spring-boot-on-k8s
spec:
  title: Spring Boot on Kubernetes
  description: Introduction to Spring Boot on Kubernetes
  content:
    image: jdk11-environment:*
    files: imgpkg+http://registry.eduk8s.svc.cluster.local:5001/lab-spring-boot-on-k8s-files:latest
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    dashboards:
    - name: Initializr
      url: $(ingress_protocol)://$(session_namespace)-initializr.$(ingress_domain)
    ingresses:
    - name: initializr
      protocol: http
      host: initializr.$(workshop_namespace).svc.cluster.local
      port: 8080
    env:
      - name: MAVEN_CACHE_IMAGE
        value: ghcr.io/vmware-tanzu-labs/lab-spring-boot-on-k8s-maven:latest
  environment:
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: initializr
        labels:
          app: initializr
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: initializr
        template:
          metadata:
            labels:
              app: initializr
          spec:
            containers:
            - name: dashboard
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:main
              imagePullPolicy: Always
              ports:
              - name: 8080-tcp
                containerPort: 8080
                protocol: TCP
    - apiVersion: v1
      kind: Service
      metadata:
        name: initializr
        labels:
          app: initializr
      spec:
        type: ClusterIP
        selector:
          app: initializr
        ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
